apiVersion: v1
kind: ConfigMap
metadata:
  name: mcpo-config
  namespace: cluster-services
data:
  config.json: |
    {
      "mcpServers": {
        "filesystem": {
          "command": "npx",
          "args": ["-y", "@modelcontextprotocol/server-filesystem", "/workspace"]
        },
        "memory": {
          "command": "npx",
          "args": ["-y", "@modelcontextprotocol/server-memory"]
        },
        "time": {
          "command": "uvx",
          "args": ["mcp-server-time"]
        },
        "puppeteer": {
          "command": "npx",
          "args": ["-y", "@modelcontextprotocol/server-puppeteer"]
        },
        "sequential-thinking": {
          "command": "npx",
          "args": ["-y", "@modelcontextprotocol/server-sequential-thinking"]
        },
        "fetch": {
          "command": "uvx",
          "args": ["mcp-server-fetch"]
        },
        "sqlite": {
          "command": "npx",
          "args": ["-y", "mcp-server-sqlite-npx", "/workspace/tasks.db"]
        },
        "github": {
          "command": "npx",
          "args": ["-y", "@modelcontextprotocol/server-github"],
          "env": {
            "GITHUB_PERSONAL_ACCESS_TOKEN": ""
          }
        },
        "homeassistant": {
          "command": "python3",
          "args": ["/workspace/homeassistant-mcp/server.py"],
          "env": {
            "HA_URL": "http://192.168.1.203:8123",
            "HA_TOKEN": "YOUR_HOME_ASSISTANT_LONG_LIVED_TOKEN",
            "HA_SSH_HOST": "192.168.1.203",
            "HA_SSH_PORT": "22",
            "HA_SSH_USER": "root",
            "HA_SSH_PASSWORD": "YOUR_SSH_PASSWORD",
            "HA_CONFIG_PATH": "/config"
          }
        }
      }
    }
